config/routes.rb
Rails.application.routes.draw do
   
  resources :students, only: [:index, :show]
  resources :pages, only: [:show]
  resources :search, only: [:index] do
    collection do
      get 'results'
    end
  end

  get ':permalink', to: 'pages#permalink'
  get 'static_about', to: 'pages#about', as: 'about'
  root to: 'students#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :teacher
  belongs_to :student

  validates :meeting_time, presence: true
end

app/models/house.rb
class House < ApplicationRecord
    has_many :students, dependent: :destroy
    has_many :teachers, dependent: :destroy

    validates :name, presence: true, uniqueness: true
    validates :points, numericality: { only_integer: true}
end

app/models/page.rb
class Page < ApplicationRecord
end

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :house
  has_many :appointments
  has_many :teachers, through: :appointment

  validates :name, presence: true
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  belongs_to :house
  has_many :appointments
  has_many :students, through: :appointment

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def permalink
        @page = Page.find_by(permalink: params[:permalink])
        if @page.nil?
            redirect_to root_url
        else
            render :show
        end
    end
    def show
        @page = Page.find(params[:id])
    end
    def about
    end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
    def index

    end
    


    def results
        @students = Student.where('name LIKE ?', "%#{params[:q]}%")
    end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  def index
    @students = Student.all
  end

  def show
    @student = Student.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hogwarts</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <h1><%= link_to 'Howard School', '/' %></h1>
      <p><%= link_to 'About Us', about_path %>
      <%= link_to 'Search', search_index_path %></p>
    </header>
    <%= yield %>
    <footer>
      <p>Copywrong 2018</p>
    </footer>
  </body>
</html>

app/views/pages/about.html.erb
<h2>About Hogwarts</h2>

<p> This is the content of the about page</p>
<p> This is even more content of the about page</p>

app/views/pages/show.html.erb
<h2><%= @page.title%></h2>
<div><%= @page.content %></div>

app/views/search/index.html.erb
<h2> Search for Students</h2>


<%= form_tag(results_search_index_path, method: "get") do %>
  <%= label_tag(:q, "Search for:") %>
  <%= text_field_tag(:q) %>
  <%= submit_tag("Search") %>
<% end %>

app/views/search/results.html.erb
<h2>Student Found: <%= @students.size %></h2>


<% if @students.empty? %>
    <p>Sorry, no students found.</p>
<% else %>
    <ul>
        <% @students.each do |student| %>
            <li><%= link_to student.name, student %></li>
        <% end %>
    </ul>
<% end %>

app/views/students/index.html.erb
<h2>All Students</h2>

<ul>
    <% @students.each do |student| %>
        <li>
            <%= link_to student.name, student %>
            <%= student.house.name %>
        </li>
    <% end %>
</ul>

app/views/students/show.html.erb
<h2><%= @student.name%></h2>

<p>
    House: <%= @student.house.name %>
</p>